server:
    port: 8001
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.driver
        url: jdbc:mysql://127.0.0.1:3306/shirodb?useunicode=true&characterencoding=utf-8&usessl=true&servertimezone=utc
        username: root
        password: admin
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
    redis:
        host: 192.168.91.128
        port: 6379
        password: 123
        timeout: 1000
        database: 0
        pool:
            max-active: 10
            max-idle: 8
            min-idle: 2
            max-wait: 100