server:
    port: 7001
spring:
    application:
        name: eureka
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka
        register-with-eureka: false
        fetch-registry: false
    instance:
        name: eureka